[metadata]
name = captcha-adversarial
version = 202505.01
author = viewstar000
description = 面向对抗的人机验证码实验项目
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
license_expression = MIT
url = https://github.com/viewstar000/captcha-adversarial
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.9
install_requires =
    numpy
    jieba
    Pillow
    torch
    torchvision
    torchaudio
    accelerate
    transformers
    sentence_transformers
    cleverhans
    openai
    gradio

[options.package_data]
* = *.md, *.txt

[options.extras_require]
dev =
    pytest
    black
    isort
